# SPINE-GPE v7 — PNADc Historical Backcast Hardening v1.1.0

Este notebook executa a auditoria e o hardening final do backcast histórico já certificado pelo engine v1.0.1.

**Estimando oficial:** soma ponderada das probabilidades do `mapping_pooled`.

**Limite:** fora dos módulos especiais, plataforma direta permanece não observada.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from pathlib import Path

ROOT = Path('/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7')
SCRIPTS = ROOT / 'scripts'
SCRIPT = SCRIPTS / 'SPINE_GPEv7_PNADC_HISTORICAL_BACKCAST_HARDENING_v1.1.0.py'
REQ = SCRIPTS / 'requirements_SPINE_GPEv7_PNADC_HISTORICAL_BACKCAST_HARDENING_v1.1.0.txt'

assert ROOT.exists(), ROOT
assert SCRIPT.exists(), SCRIPT
assert REQ.exists(), REQ
print('ROOT:', ROOT)
print('SCRIPT:', SCRIPT)

ROOT: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7
SCRIPT: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/scripts/SPINE_GPEv7_PNADC_HISTORICAL_BACKCAST_HARDENING_v1.1.0.py

In [3]:
import subprocess, sys

install = subprocess.run(
    [sys.executable, '-m', 'pip', 'install', '-q', '-r', str(REQ)],
    text=True,
    capture_output=True,
    check=False,
)
print(install.stdout)
print(install.stderr)
print('Install exit code:', install.returncode)
assert install.returncode == 0

Install exit code: 0

## 1. Auditoria leve

Valida lock upstream, hashes, parser e layouts antes do ajuste de qualquer modelo.

In [4]:
audit = subprocess.run(
    [
        sys.executable, str(SCRIPT),
        '--root', str(ROOT),
        '--mode', 'audit',
        '--strict',
    ],
    text=True,
    capture_output=True,
    check=False,
)
print(audit.stdout)
print(audit.stderr)
print('Audit exit code:', audit.returncode)

{
  "run_id": "20260724T171058Z",
  "script_version": "1.1.0",
  "schema_version": "spine-gpe-v7-pnadc-historical-backcast-hardening-1.1.0",
  "mode": "audit",
  "status": "AUDIT_PASSED",
  "critical_failures": [],
  "warnings": [
    {
      "test_id": "layout.independent_year_versions",
      "status": "WARN",
      "severity": "high",
      "message": "Somente uma ou nenhuma versão anual independente foi localizada; equivalência semântica anual permanece documentada como limitação.",
      "observed": [
        "2022"
      ],
      "expected": ">=2 annual versions",
      "evidence": null
    }
  ],
  "layout_matrix": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_layout_equivalence_matrix_20260724T171058Z.csv",
  "upstream_lock": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/PNADC_HISTORICAL_PROXY_CERTIFICATION_LOCK.json",
  "created_at_utc": "2026-07-24T17:11:26.591264+00:00"
}

2026-07-24 17:10:58,996 | INFO | SPINE-GPE PNADc Backcast Hardening v1.1.0 | root=/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7 | mode=audit
2026-07-24 17:11:26,606 | INFO | Auditoria do hardening concluída | status=AUDIT_PASSED

Audit exit code: 0

In [5]:
import json

AUDIT_LOCK = ROOT / '00_admin' / 'PNADC_HISTORICAL_BACKCAST_HARDENING_AUDIT_LOCK.json'
audit_lock = json.loads(AUDIT_LOCK.read_text(encoding='utf-8'))
print(json.dumps(audit_lock, ensure_ascii=False, indent=2))
assert audit_lock['status'] == 'AUDIT_PASSED', audit_lock['critical_failures']

{
  "run_id": "20260724T171058Z",
  "script_version": "1.1.0",
  "schema_version": "spine-gpe-v7-pnadc-historical-backcast-hardening-1.1.0",
  "mode": "audit",
  "status": "AUDIT_PASSED",
  "critical_failures": [],
  "warnings": [
    {
      "test_id": "layout.independent_year_versions",
      "status": "WARN",
      "severity": "high",
      "message": "Somente uma ou nenhuma versão anual independente foi localizada; equivalência semântica anual permanece documentada como limitação.",
      "observed": [
        "2022"
      ],
      "expected": ">=2 annual versions",
      "evidence": null
    }
  ],
  "layout_matrix": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_layout_equivalence_matrix_20260724T171058Z.csv",
  "upstream_lock": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/PNADC_HISTORICAL_PROXY_CERTIFICATION_LOCK.json",
  "created_at_utc": "2026-07-24T17:11:26.591264+00:00"
}

## 2. Hardening completo

A execução abaixo usa 30 réplicas de bootstrap. Para uma checagem rápida de engenharia, reduza temporariamente para 5. Para o lock final, preserve 30 ou aumente para 100 se houver tempo computacional.

In [6]:
full = subprocess.run(
    [
        sys.executable, str(SCRIPT),
        '--root', str(ROOT),
        '--mode', 'full',
        '--calibration-folds', '5',
        '--bootstrap-calibration-folds', '3',
        '--bootstrap-reps', '30',
        '--mca-components', '8',
        '--cluster-k-min', '4',
        '--cluster-k-max', '8',
        '--strict',
    ],
    text=True,
    capture_output=True,
    check=False,
)
print(full.stdout)
print(full.stderr)
print('Full exit code:', full.returncode)

{
  "run_id": "20260724T171145Z",
  "script_version": "1.1.0",
  "schema_version": "spine-gpe-v7-pnadc-historical-backcast-hardening-1.1.0",
  "validation_schema_version": "spine-gpe-v7-pnadc-backcast-validation-1.1.0",
  "model_schema_version": "spine-gpe-v7-pnadc-backcast-model-1.1.0",
  "mode": "full",
  "status": "FINAL_CERTIFIED",
  "critical_failures": [],
  "warnings": [
    {
      "test_id": "layout.independent_year_versions",
      "status": "WARN",
      "severity": "high",
      "message": "Somente uma ou nenhuma versão anual independente foi localizada; equivalência semântica anual permanece documentada como limitação.",
      "observed": [
        "2022"
      ],
      "expected": ">=2 annual versions",
      "evidence": null
    },
    {
      "test_id": "temporal.2022_to_2024.calibration_slope",
      "status": "WARN",
      "severity": "high",
      "message": "Slope fora de 0,75–1,25; interpretar probabilidades com cautela.",
      "observed": null,
      "expected": "0.75<=slope<=1.25",
      "evidence": null
    },
    {
      "test_id": "temporal.2024_to_2022.calibration_slope",
      "status": "WARN",
      "severity": "high",
      "message": "Slope fora de 0,75–1,25; interpretar probabilidades com cautela.",
      "observed": null,
      "expected": "0.75<=slope<=1.25",
      "evidence": null
    },
    {
      "test_id": "knn.2019q1.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.22680550758052248,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2019q2.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.24042625606457754,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2019q3.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.22218605767406818,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2019q4.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.21878371920495837,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2020q1.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.21910599441828246,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2020q2.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.23070202107892127,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2020q3.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.23222315828639623,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2020q4.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.23981559991997303,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2021q1.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.24824374373937033,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2021q2.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.2413092380200281,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2021q3.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.23007779268590256,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2021q4.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.21858275276019695,
      "expected": ">=0.7",
      "evidence": null
    }
  ],
  "upstream_historical_lock": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/PNADC_HISTORICAL_PROXY_CERTIFICATION_LOCK.json",
  "upstream_historical_run_id": "20260723T131540Z",
  "historical_periods": [
    "2019q1",
    "2019q2",
    "2019q3",
    "2019q4",
    "2020q1",
    "2020q2",
    "2020q3",
    "2020q4",
    "2021q1",
    "2021q2",
    "2021q3",
    "2021q4"
  ],
  "primary_model": "mapping_pooled",
  "sensitivity_models": [
    "mapping_2022",
    "mapping_2024",
    "weighted_knn_k50"
  ],
  "primary_features": [
    "occupation_code",
    "activity_code",
    "position_code"
  ],
  "artifacts": {
    "table": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening",
    "model": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_backcast_hardening",
    "report": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_backcast_hardening",
    "registry": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/registry",
    "layout": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_layout_equivalence_matrix_20260724T171145Z.csv",
    "metrics": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_temporal_calibrated_metrics_20260724T171145Z.csv",
    "reliability": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_reliability_deciles_20260724T171145Z.csv",
    "toprisk": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_top_risk_20260724T171145Z.csv",
    "goldens": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_direct_aggregate_goldens_20260724T171145Z.csv",
    "mca_categories": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_mca_category_coordinates_20260724T171145Z.csv",
    "mca_cells": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_mca_historical_cell_coordinates_20260724T171145Z.csv",
    "support": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_transport_support_20260724T171145Z.csv",
    "support_summary": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_backcast_support_summary_20260724T171145Z.csv",
    "cluster_cells": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_cell_typologies_20260724T171145Z.csv",
    "cluster_eval": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_cluster_selection_20260724T171145Z.csv",
    "cluster_stability": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_cluster_stability_20260724T171145Z.csv",
    "cluster_profiles": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_cluster_profiles_20260724T171145Z.csv",
    "knn_metrics": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_weighted_knn_benchmark_20260724T171145Z.csv",
    "divergence": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_logit_knn_divergence_20260724T171145Z.csv",
    "mapping_2022": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_backcast_mapping_2022_20260724T171145Z.csv",
    "mapping_2024": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_backcast_mapping_2024_20260724T171145Z.csv",
    "mapping_pooled": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_backcast_mapping_pooled_20260724T171145Z.csv",
    "survey_uncertainty": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_survey_uncertainty_20260724T171145Z.csv",
    "bootstrap_raw": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_model_bootstrap_replicates_20260724T171145Z.csv",
    "bootstrap_summary": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_model_uncertainty_20260724T171145Z.csv",
    "transport": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_transport_sensitivity_20260724T171145Z.csv",
    "final_estimates": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_backcast_final_estimates_20260724T171145Z.csv",
    "bundle": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_backcast_hardening/pnadc_historical_backcast_hardening_bundle_20260724T171145Z.joblib",
    "model_card": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_backcast_hardening/pnadc_historical_backcast_model_card_20260724T171145Z.md",
    "report_file": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_backcast_hardening/pnadc_historical_backcast_hardening_report_20260724T171145Z.md",
    "registry_file": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/registry/pnadc_historical_backcast_hardening_registry_20260724T171145Z.json"
  },
  "artifact_hashes": {
    "layout": "4c92b81e6a2d525572ff455e6f4c511c5731604d6871d743313da4e628614134",
    "metrics": "c0ff5541c5292a0217238609cfb23b2dfdcf1900738f5094c3801bd5cf44de4c",
    "reliability": "2efc7c889ff4cc2035106f2f4222bc99cd2522d91a8197117cc6c0b5a19a8809",
    "toprisk": "d8b7ca4b7768c2ded5f5142e644b96b43cfa4ff6c114ff93f26247efbe0bf2aa",
    "goldens": "0eb8bbebde9828ba496ac01db99930407a4abfb28ce4b442f3b011f567d89c50",
    "mca_categories": "8b3d3d17144d9c5379bf7698c08ea57b58ced391ac0b73d52d462d3ee76e21e9",
    "mca_cells": "fa00a66a01a8d917b274daaa3a30a49cee01b1ac823e55d6d6e27f6e0dd1ddbd",
    "support": "fa00a66a01a8d917b274daaa3a30a49cee01b1ac823e55d6d6e27f6e0dd1ddbd",
    "support_summary": "fe8ab84799f03cb10e200ccf6c9c4560e930f5faaf50273ad825b695d3f160e0",
    "cluster_cells": "a798eea60ae705eae2306eb1149ae235739320740f7fc88fef7f90829f12a863",
    "cluster_eval": "5bf76d95b1fc9c86623b1a5054afab50a1feb92810812247b8f8b26f1a179d0f",
    "cluster_stability": "44664f076435ec6b4698e987a86f1e7410e5bf5e8d75a276014a92c109b62315",
    "cluster_profiles": "e0681e22adae28e6e9d87f402900fb9f1dcf136dd281464aae8c2e0add9e4a96",
    "knn_metrics": "c2ba9ff07acc18389db184eaf7c1dc8d14ba005618742b5d319ee11c944888a5",
    "divergence": "0b316825d624a83bbf7aa0f7e83eeae7cbe03695aa1c20737421b6396133b040",
    "mapping_2022": "ae13bc07e429702ef8c4dbe29c6944c53ae8032570e8e3effa70d63faf1ec82d",
    "mapping_2024": "959ec04b4b981218161b720bb9de0d5e382c22147c3efd6f39a363b726c1575b",
    "mapping_pooled": "cfea3edbdab2409293ec3d27929ebd4b726626aa8a8f7e873779d8803e7edff3",
    "survey_uncertainty": "ee94454c3e130f5af277cc811b3f9ae2bcc6b8e3760b0ebb9dd508d88e288944",
    "bootstrap_raw": "239c7a506609afc5dfca4566158fbafd4a30e096f203527b629f028b8da0eeba",
    "bootstrap_summary": "5b1e03b21025bfe224da3c4e6a6847241bb10c8cfd4e13327248da170ed10ebe",
    "transport": "566b27b873655118065308c6fcfa18ddb0ccad8dc8d2e220ebceed8b8c28e39d",
    "final_estimates": "2dd6c3377819afee2d78f637b3e1488767887a80a97004f474f3c47479b475da",
    "bundle": "42218fb582ce3b1d2cf6563b0944ccd8cbfebdc1ed4cd889506f2ceb93b8cb76",
    "model_card": "e462dbdcbf7df608e2179abef085959b0ae9aa771f6715e2bec372a1465c711c",
    "report_file": "eca3c0f0c23a4b2704358c88c88bf486aeb9a0bf839eb6a45cfb9ebb5bdbf304",
    "registry_file": "01b6fe959205fb9ca30105f40d8f4cf86ccc0f2c108a2e0bfd902ee51f194393"
  },
  "epistemic_limit": "Probabilidade histórica modelada; plataforma direta permanece não observada fora dos módulos especiais.",
  "claim_ceiling": "Reconstrução retrospectiva probabilística agregada da compatibilidade histórica com entrega por plataforma, calibrada em 2022T4/2024T3, com incerteza e suporte explicitados.",
  "created_at_utc": "2026-07-24T17:17:02.270128+00:00"
}
STATUS: FINAL_CERTIFIED
REPORT: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_backcast_hardening/pnadc_historical_backcast_hardening_report_20260724T171145Z.md
FINAL ESTIMATES: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_backcast_final_estimates_20260724T171145Z.csv
MODEL BUNDLE: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_backcast_hardening/pnadc_historical_backcast_hardening_bundle_20260724T171145Z.joblib

2026-07-24 17:11:45,248 | INFO | SPINE-GPE PNADc Backcast Hardening v1.1.0 | root=/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7 | mode=full
2026-07-24 17:11:58,487 | INFO | Histórico carregado | 2019q1 | registros=201434 | células-PSU=170230
2026-07-24 17:12:03,326 | INFO | Histórico carregado | 2019q2 | registros=203203 | células-PSU=171432
2026-07-24 17:12:06,971 | INFO | Histórico carregado | 2019q3 | registros=202679 | células-PSU=171215
2026-07-24 17:12:11,214 | INFO | Histórico carregado | 2019q4 | registros=201237 | células-PSU=170473
2026-07-24 17:12:16,674 | INFO | Histórico carregado | 2020q1 | registros=177234 | células-PSU=150721
2026-07-24 17:12:19,826 | INFO | Histórico carregado | 2020q2 | registros=119921 | células-PSU=104526
2026-07-24 17:12:22,720 | INFO | Histórico carregado | 2020q3 | registros=117589 | células-PSU=102198
2026-07-24 17:12:24,806 | INFO | Histórico carregado | 2020q4 | registros=112149 | células-PSU=97636
2026-07-24 17:12:26,894 | INFO | Histórico carregado | 2021q1 | registros=106865 | células-PSU=92929
2026-07-24 17:12:31,391 | INFO | Histórico carregado | 2021q2 | registros=122229 | células-PSU=105639
2026-07-24 17:12:34,377 | INFO | Histórico carregado | 2021q3 | registros=155713 | células-PSU=133250
2026-07-24 17:12:37,357 | INFO | Histórico carregado | 2021q4 | registros=168659 | células-PSU=144463
2026-07-24 17:12:37,795 | INFO | Ajustando mapping 2022
2026-07-24 17:12:42,035 | INFO | Ajustando mapping 2024
2026-07-24 17:12:47,033 | INFO | Ajustando mapping pooled
2026-07-24 17:13:04,845 | INFO | Ajustando MCA ponderada em 20624 células diretas
2026-07-24 17:13:11,090 | INFO | Selecionando tipologias no espaço MCA
2026-07-24 17:13:18,354 | INFO | Selecionando KNN ponderado temporal
2026-07-24 17:14:30,233 | INFO | Bootstrap de modelo 1/30 concluído
2026-07-24 17:14:35,173 | INFO | Bootstrap de modelo 2/30 concluído
2026-07-24 17:14:39,856 | INFO | Bootstrap de modelo 3/30 concluído
2026-07-24 17:14:46,233 | INFO | Bootstrap de modelo 4/30 concluído
2026-07-24 17:14:50,778 | INFO | Bootstrap de modelo 5/30 concluído
2026-07-24 17:14:55,260 | INFO | Bootstrap de modelo 6/30 concluído
2026-07-24 17:15:01,630 | INFO | Bootstrap de modelo 7/30 concluído
2026-07-24 17:15:06,233 | INFO | Bootstrap de modelo 8/30 concluído
2026-07-24 17:15:10,774 | INFO | Bootstrap de modelo 9/30 concluído
2026-07-24 17:15:17,250 | INFO | Bootstrap de modelo 10/30 concluído
2026-07-24 17:15:21,786 | INFO | Bootstrap de modelo 11/30 concluído
2026-07-24 17:15:26,184 | INFO | Bootstrap de modelo 12/30 concluído
2026-07-24 17:15:32,750 | INFO | Bootstrap de modelo 13/30 concluído
2026-07-24 17:15:37,213 | INFO | Bootstrap de modelo 14/30 concluído
2026-07-24 17:15:41,959 | INFO | Bootstrap de modelo 15/30 concluído
2026-07-24 17:15:48,299 | INFO | Bootstrap de modelo 16/30 concluído
2026-07-24 17:15:52,787 | INFO | Bootstrap de modelo 17/30 concluído
2026-07-24 17:15:57,541 | INFO | Bootstrap de modelo 18/30 concluído
2026-07-24 17:16:03,747 | INFO | Bootstrap de modelo 19/30 concluído
2026-07-24 17:16:08,366 | INFO | Bootstrap de modelo 20/30 concluído
2026-07-24 17:16:13,450 | INFO | Bootstrap de modelo 21/30 concluído
2026-07-24 17:16:19,246 | INFO | Bootstrap de modelo 22/30 concluído
2026-07-24 17:16:23,711 | INFO | Bootstrap de modelo 23/30 concluído
2026-07-24 17:16:28,895 | INFO | Bootstrap de modelo 24/30 concluído
2026-07-24 17:16:34,718 | INFO | Bootstrap de modelo 25/30 concluído
2026-07-24 17:16:39,397 | INFO | Bootstrap de modelo 26/30 concluído
2026-07-24 17:16:45,191 | INFO | Bootstrap de modelo 27/30 concluído
2026-07-24 17:16:50,503 | INFO | Bootstrap de modelo 28/30 concluído
2026-07-24 17:16:55,004 | INFO | Bootstrap de modelo 29/30 concluído
2026-07-24 17:17:00,736 | INFO | Bootstrap de modelo 30/30 concluído
2026-07-24 17:17:02,413 | INFO | Hardening concluído | status=FINAL_CERTIFIED

Full exit code: 0

In [7]:
LOCK = ROOT / '00_admin' / 'PNADC_HISTORICAL_BACKCAST_HARDENING_LOCK.json'
lock = json.loads(LOCK.read_text(encoding='utf-8'))
print(json.dumps(lock, ensure_ascii=False, indent=2))
print('STATUS:', lock['status'])
print('Critical failures:', len(lock.get('critical_failures', [])))
print('Warnings:', len(lock.get('warnings', [])))

{
  "run_id": "20260724T171145Z",
  "script_version": "1.1.0",
  "schema_version": "spine-gpe-v7-pnadc-historical-backcast-hardening-1.1.0",
  "validation_schema_version": "spine-gpe-v7-pnadc-backcast-validation-1.1.0",
  "model_schema_version": "spine-gpe-v7-pnadc-backcast-model-1.1.0",
  "mode": "full",
  "status": "FINAL_CERTIFIED",
  "critical_failures": [],
  "warnings": [
    {
      "test_id": "layout.independent_year_versions",
      "status": "WARN",
      "severity": "high",
      "message": "Somente uma ou nenhuma versão anual independente foi localizada; equivalência semântica anual permanece documentada como limitação.",
      "observed": [
        "2022"
      ],
      "expected": ">=2 annual versions",
      "evidence": null
    },
    {
      "test_id": "temporal.2022_to_2024.calibration_slope",
      "status": "WARN",
      "severity": "high",
      "message": "Slope fora de 0,75–1,25; interpretar probabilidades com cautela.",
      "observed": null,
      "expected": "0.75<=slope<=1.25",
      "evidence": null
    },
    {
      "test_id": "temporal.2024_to_2022.calibration_slope",
      "status": "WARN",
      "severity": "high",
      "message": "Slope fora de 0,75–1,25; interpretar probabilidades com cautela.",
      "observed": null,
      "expected": "0.75<=slope<=1.25",
      "evidence": null
    },
    {
      "test_id": "knn.2019q1.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.22680550758052248,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2019q2.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.24042625606457754,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2019q3.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.22218605767406818,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2019q4.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.21878371920495837,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2020q1.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.21910599441828246,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2020q2.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.23070202107892127,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2020q3.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.23222315828639623,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2020q4.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.23981559991997303,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2021q1.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.24824374373937033,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2021q2.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.2413092380200281,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2021q3.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.23007779268590256,
      "expected": ">=0.7",
      "evidence": null
    },
    {
      "test_id": "knn.2021q4.rank",
      "status": "WARN",
      "severity": "high",
      "message": "Baixa correlação de ranking entre logística e KNN.",
      "observed": 0.21858275276019695,
      "expected": ">=0.7",
      "evidence": null
    }
  ],
  "upstream_historical_lock": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/PNADC_HISTORICAL_PROXY_CERTIFICATION_LOCK.json",
  "upstream_historical_run_id": "20260723T131540Z",
  "historical_periods": [
    "2019q1",
    "2019q2",
    "2019q3",
    "2019q4",
    "2020q1",
    "2020q2",
    "2020q3",
    "2020q4",
    "2021q1",
    "2021q2",
    "2021q3",
    "2021q4"
  ],
  "primary_model": "mapping_pooled",
  "sensitivity_models": [
    "mapping_2022",
    "mapping_2024",
    "weighted_knn_k50"
  ],
  "primary_features": [
    "occupation_code",
    "activity_code",
    "position_code"
  ],
  "artifacts": {
    "table": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening",
    "model": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_backcast_hardening",
    "report": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_backcast_hardening",
    "registry": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/registry",
    "layout": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_layout_equivalence_matrix_20260724T171145Z.csv",
    "metrics": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_temporal_calibrated_metrics_20260724T171145Z.csv",
    "reliability": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_reliability_deciles_20260724T171145Z.csv",
    "toprisk": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_top_risk_20260724T171145Z.csv",
    "goldens": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_direct_aggregate_goldens_20260724T171145Z.csv",
    "mca_categories": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_mca_category_coordinates_20260724T171145Z.csv",
    "mca_cells": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_mca_historical_cell_coordinates_20260724T171145Z.csv",
    "support": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_transport_support_20260724T171145Z.csv",
    "support_summary": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_backcast_support_summary_20260724T171145Z.csv",
    "cluster_cells": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_cell_typologies_20260724T171145Z.csv",
    "cluster_eval": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_cluster_selection_20260724T171145Z.csv",
    "cluster_stability": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_cluster_stability_20260724T171145Z.csv",
    "cluster_profiles": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_cluster_profiles_20260724T171145Z.csv",
    "knn_metrics": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_weighted_knn_benchmark_20260724T171145Z.csv",
    "divergence": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_logit_knn_divergence_20260724T171145Z.csv",
    "mapping_2022": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_backcast_mapping_2022_20260724T171145Z.csv",
    "mapping_2024": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_backcast_mapping_2024_20260724T171145Z.csv",
    "mapping_pooled": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_backcast_mapping_pooled_20260724T171145Z.csv",
    "survey_uncertainty": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_survey_uncertainty_20260724T171145Z.csv",
    "bootstrap_raw": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_model_bootstrap_replicates_20260724T171145Z.csv",
    "bootstrap_summary": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_model_uncertainty_20260724T171145Z.csv",
    "transport": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_transport_sensitivity_20260724T171145Z.csv",
    "final_estimates": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_backcast_final_estimates_20260724T171145Z.csv",
    "bundle": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_backcast_hardening/pnadc_historical_backcast_hardening_bundle_20260724T171145Z.joblib",
    "model_card": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_backcast_hardening/pnadc_historical_backcast_model_card_20260724T171145Z.md",
    "report_file": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_backcast_hardening/pnadc_historical_backcast_hardening_report_20260724T171145Z.md",
    "registry_file": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/registry/pnadc_historical_backcast_hardening_registry_20260724T171145Z.json"
  },
  "artifact_hashes": {
    "layout": "4c92b81e6a2d525572ff455e6f4c511c5731604d6871d743313da4e628614134",
    "metrics": "c0ff5541c5292a0217238609cfb23b2dfdcf1900738f5094c3801bd5cf44de4c",
    "reliability": "2efc7c889ff4cc2035106f2f4222bc99cd2522d91a8197117cc6c0b5a19a8809",
    "toprisk": "d8b7ca4b7768c2ded5f5142e644b96b43cfa4ff6c114ff93f26247efbe0bf2aa",
    "goldens": "0eb8bbebde9828ba496ac01db99930407a4abfb28ce4b442f3b011f567d89c50",
    "mca_categories": "8b3d3d17144d9c5379bf7698c08ea57b58ced391ac0b73d52d462d3ee76e21e9",
    "mca_cells": "fa00a66a01a8d917b274daaa3a30a49cee01b1ac823e55d6d6e27f6e0dd1ddbd",
    "support": "fa00a66a01a8d917b274daaa3a30a49cee01b1ac823e55d6d6e27f6e0dd1ddbd",
    "support_summary": "fe8ab84799f03cb10e200ccf6c9c4560e930f5faaf50273ad825b695d3f160e0",
    "cluster_cells": "a798eea60ae705eae2306eb1149ae235739320740f7fc88fef7f90829f12a863",
    "cluster_eval": "5bf76d95b1fc9c86623b1a5054afab50a1feb92810812247b8f8b26f1a179d0f",
    "cluster_stability": "44664f076435ec6b4698e987a86f1e7410e5bf5e8d75a276014a92c109b62315",
    "cluster_profiles": "e0681e22adae28e6e9d87f402900fb9f1dcf136dd281464aae8c2e0add9e4a96",
    "knn_metrics": "c2ba9ff07acc18389db184eaf7c1dc8d14ba005618742b5d319ee11c944888a5",
    "divergence": "0b316825d624a83bbf7aa0f7e83eeae7cbe03695aa1c20737421b6396133b040",
    "mapping_2022": "ae13bc07e429702ef8c4dbe29c6944c53ae8032570e8e3effa70d63faf1ec82d",
    "mapping_2024": "959ec04b4b981218161b720bb9de0d5e382c22147c3efd6f39a363b726c1575b",
    "mapping_pooled": "cfea3edbdab2409293ec3d27929ebd4b726626aa8a8f7e873779d8803e7edff3",
    "survey_uncertainty": "ee94454c3e130f5af277cc811b3f9ae2bcc6b8e3760b0ebb9dd508d88e288944",
    "bootstrap_raw": "239c7a506609afc5dfca4566158fbafd4a30e096f203527b629f028b8da0eeba",
    "bootstrap_summary": "5b1e03b21025bfe224da3c4e6a6847241bb10c8cfd4e13327248da170ed10ebe",
    "transport": "566b27b873655118065308c6fcfa18ddb0ccad8dc8d2e220ebceed8b8c28e39d",
    "final_estimates": "2dd6c3377819afee2d78f637b3e1488767887a80a97004f474f3c47479b475da",
    "bundle": "42218fb582ce3b1d2cf6563b0944ccd8cbfebdc1ed4cd889506f2ceb93b8cb76",
    "model_card": "e462dbdcbf7df608e2179abef085959b0ae9aa771f6715e2bec372a1465c711c",
    "report_file": "eca3c0f0c23a4b2704358c88c88bf486aeb9a0bf839eb6a45cfb9ebb5bdbf304",
    "registry_file": "01b6fe959205fb9ca30105f40d8f4cf86ccc0f2c108a2e0bfd902ee51f194393"
  },
  "epistemic_limit": "Probabilidade histórica modelada; plataforma direta permanece não observada fora dos módulos especiais.",
  "claim_ceiling": "Reconstrução retrospectiva probabilística agregada da compatibilidade histórica com entrega por plataforma, calibrada em 2022T4/2024T3, com incerteza e suporte explicitados.",
  "created_at_utc": "2026-07-24T17:17:02.270128+00:00"
}
STATUS: FINAL_CERTIFIED
Critical failures: 0
Warnings: 15

## 3. Inspeção dos resultados

As células seguintes exibem métricas temporais, golden totals, estimativas finais, suporte e divergência logística × KNN.

In [8]:
import pandas as pd

artifacts = lock.get('artifacts', {})
for key in [
    'metrics', 'goldens', 'final_estimates', 'support_summary',
    'divergence', 'bootstrap_summary', 'layout'
]:
    print(key, '=>', artifacts.get(key))

metrics => /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_temporal_calibrated_metrics_20260724T171145Z.csv
goldens => /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_direct_aggregate_goldens_20260724T171145Z.csv
final_estimates => /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_backcast_final_estimates_20260724T171145Z.csv
support_summary => /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_backcast_support_summary_20260724T171145Z.csv
divergence => /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_logit_knn_divergence_20260724T171145Z.csv
bootstrap_summary => /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_proxy_model_uncertainty_20260724T171145Z.csv
layout => /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_layout_equivalence_matrix_20260724T171145Z.csv

In [9]:
metrics = pd.read_csv(artifacts['metrics'])
metrics

,model,train_year,test_year,n,n_positive_unweighted,weighted_prevalence,roc_auc,average_precision,brier,null_brier,brier_skill,log_loss,ece_10,ece_relative_prevalence,calibration_intercept,calibration_slope
0,mapping_2022,2022,2024,184157,778,0.005505,0.978834,0.363988,0.004009,0.005475,0.267681,0.016646,0.000214,0.038874,NaN,NaN
1,mapping_2024,2024,2022,178163,691,0.005208,0.979361,0.316580,0.003948,0.005181,0.238089,0.016682,0.000139,0.026638,NaN,NaN

In [10]:
goldens = pd.read_csv(artifacts['goldens'])
goldens

,year,model,direct_total,direct_total_se,direct_share,direct_share_se,model_total,model_total_se_conditional,model_share,model_share_se_conditional,difference_absolute,difference_relative,predicted_to_observed_ratio
0,2022,mapping_2022,445866.911584,26056.331061,0.005208,0.000302,442641.594557,14564.168938,0.005171,0.000166,-3225.317027,-0.007234,0.992766
1,2022,mapping_2024,445866.911584,26056.331061,0.005208,0.000302,453191.798549,13603.319894,0.005294,0.000156,7324.886965,0.016428,1.016428
2,2022,mapping_pooled,445866.911584,26056.331061,0.005208,0.000302,451993.207293,13886.090428,0.005280,0.000158,6126.295709,0.013740,1.013740
3,2024,mapping_2022,487284.887116,25149.948865,0.005505,0.000283,470387.153259,13164.554609,0.005314,0.000146,-16897.733857,-0.034677,0.965323
4,2024,mapping_2024,487284.887116,25149.948865,0.005505,0.000283,488093.388075,13915.516473,0.005514,0.000154,808.500958,0.001659,1.001659
5,2024,mapping_pooled,487284.887116,25149.948865,0.005505,0.000283,482905.058534,13529.423674,0.005456,0.000150,-4379.828582,-0.008988,0.991012

In [11]:
final_estimates = pd.read_csv(artifacts['final_estimates'])
final_estimates

,source_period,total_2022,total_se_survey_2022,share_2022,share_se_survey_2022,total_2024,total_se_survey_2024,share_2024,share_se_survey_2024,total_pooled,...,model_share_p975,total_se_survey_plus_model,share_se_survey_plus_model,share_ci95_lower_survey_plus_model,share_ci95_upper_survey_plus_model,total_ci95_lower_survey_plus_model,total_ci95_upper_survey_plus_model,claim_status,direct_platform_observed,evidence_tier
0,2019q1,307848.950745,7673.296916,0.003837,0.000094,321739.166716,7494.880663,0.004011,0.000092,317478.603902,...,0.004249,16414.528780,0.000204,0.003558,0.004357,285306.127494,349651.080311,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
1,2019q2,310956.762109,6930.421512,0.003821,0.000084,329373.770203,7590.596554,0.004047,0.000092,322971.633478,...,0.004248,15991.800943,0.000196,0.003584,0.004352,291627.703631,354315.563325,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
2,2019q3,332537.699466,8062.022684,0.004061,0.000097,347906.341214,8472.661143,0.004249,0.000102,342236.920247,...,0.004464,16936.437037,0.000206,0.003776,0.004584,309041.503655,375432.336838,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
3,2019q4,348864.331314,9976.049668,0.004220,0.000117,361810.591683,9714.643998,0.004376,0.000114,358152.489032,...,0.004604,17982.343244,0.000215,0.003910,0.004754,322907.096274,393397.881789,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
4,2020q1,346095.794941,10344.648076,0.004309,0.000126,357607.258125,10177.590542,0.004453,0.000124,355182.969437,...,0.004704,18202.208747,0.000225,0.003981,0.004864,319506.640292,390859.298581,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
5,2020q2,343226.854878,13772.841006,0.004844,0.000192,355449.121986,13954.212102,0.005017,0.000195,352728.846651,...,0.005246,18738.257571,0.000263,0.004463,0.005493,316001.861811,389455.831491,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
6,2020q3,350976.691152,15152.451472,0.004962,0.000211,359452.277036,14689.958438,0.005082,0.000204,360248.481674,...,0.005312,19458.093910,0.000272,0.004559,0.005627,322110.617610,398386.345737,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
7,2020q4,349085.626281,14675.164721,0.004705,0.000196,360010.213908,13841.860917,0.004853,0.000184,358670.590713,...,0.005053,18875.207742,0.000253,0.004340,0.005329,321675.183537,395665.997888,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
8,2021q1,370011.575193,17555.627446,0.004981,0.000234,388282.173589,19025.842729,0.005227,0.000253,383733.366363,...,0.005412,22333.602565,0.000298,0.004580,0.005751,339959.505335,427507.227391,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
9,2021q2,394196.946396,14786.349696,0.005154,0.000190,417108.094612,15825.376178,0.005453,0.000204,410629.575872,...,0.005625,20487.074717,0.000266,0.004848,0.005889,370474.909428,450784.242317,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
10,2021q3,410106.695517,11791.978050,0.005108,0.000145,431807.850203,12529.809620,0.005378,0.000153,426434.774952,...,0.005566,18849.660691,0.000233,0.004854,0.005768,389489.439998,463380.109906,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C
11,2021q4,437883.923811,13218.101134,0.005287,0.000157,456382.140996,13727.278158,0.005511,0.000162,452057.951077,...,0.005711,19927.317373,0.000238,0.004991,0.005926,413000.409025,491115.493128,MODEL_BASED_HISTORICAL_COMPATIBILITY,False,C

In [12]:
support = pd.read_csv(artifacts['support_summary'])
support

,source_period,support_class,weighted_population,population_share,expected_total_pooled,expected_total_share,n_psu_cells
0,2019q1,STRONG,7.408039e+07,0.923450,309586.727008,0.975142,157641
1,2019q1,MODERATE,5.245708e+06,0.065390,4450.889626,0.014019,10696
2,2019q1,WEAK,6.349389e+05,0.007915,3363.017416,0.010593,1276
3,2019q1,OUT_OF_SUPPORT,2.602860e+05,0.003245,77.969851,0.000246,617
4,2019q2,STRONG,7.539692e+07,0.926373,315193.309363,0.975916,159218
5,2019q2,MODERATE,5.099524e+06,0.062656,4463.370041,0.013820,10320
6,2019q2,WEAK,6.821675e+05,0.008382,3071.223575,0.009509,1374
7,2019q2,OUT_OF_SUPPORT,2.107708e+05,0.002590,243.730499,0.000755,520
8,2019q3,STRONG,7.574863e+07,0.925099,334841.468956,0.978391,158994
9,2019q3,MODERATE,5.226130e+06,0.063825,4570.872414,0.013356,10363
10,2019q3,WEAK,6.745266e+05,0.008238,2701.824292,0.007895,1355
11,2019q3,OUT_OF_SUPPORT,2.323848e+05,0.002838,122.754585,0.000359,503
12,2019q4,STRONG,7.645512e+07,0.924748,351649.205874,0.981842,158271
13,2019q4,MODERATE,5.285764e+06,0.063933,4038.431504,0.011276,10283
14,2019q4,WEAK,7.072043e+05,0.008554,2358.675266,0.006586,1404
15,2019q4,OUT_OF_SUPPORT,2.286630e+05,0.002766,106.176387,0.000296,515
16,2020q1,STRONG,7.454601e+07,0.928181,349138.941309,0.982983,140388
17,2020q1,MODERATE,4.943948e+06,0.061558,3398.739381,0.009569,8873
18,2020q1,WEAK,6.179442e+05,0.007694,2401.718872,0.006762,1074
19,2020q1,OUT_OF_SUPPORT,2.061807e+05,0.002567,243.569875,0.000686,386
20,2020q2,STRONG,6.571220e+07,0.927413,347877.779240,0.986247,97418
21,2020q2,MODERATE,4.375497e+06,0.061752,3293.331300,0.009337,6102
22,2020q2,WEAK,6.079467e+05,0.008580,1496.690874,0.004243,765
23,2020q2,OUT_OF_SUPPORT,1.597588e+05,0.002255,61.045238,0.000173,241
24,2020q3,STRONG,6.574233e+07,0.929444,354958.089301,0.985315,95478
25,2020q3,MODERATE,4.345923e+06,0.061441,3046.815380,0.008458,5760
26,2020q3,WEAK,4.939012e+05,0.006983,2194.940670,0.006093,733
27,2020q3,OUT_OF_SUPPORT,1.507815e+05,0.002132,48.636323,0.000135,227
28,2020q4,STRONG,6.882938e+07,0.927752,354049.769656,0.987117,91233
29,2020q4,MODERATE,4.571713e+06,0.061622,2727.061387,0.007603,5427
30,2020q4,WEAK,6.085170e+05,0.008202,1840.243198,0.005131,718
31,2020q4,OUT_OF_SUPPORT,1.797941e+05,0.002423,53.516472,0.000149,258
32,2021q1,STRONG,6.899780e+07,0.928784,377741.497662,0.984385,86817
33,2021q1,MODERATE,4.539299e+06,0.061104,3018.235505,0.007865,5201
34,2021q1,WEAK,5.180348e+05,0.006973,2907.903371,0.007578,643
35,2021q1,OUT_OF_SUPPORT,2.331432e+05,0.003138,65.729825,0.000171,268
36,2021q2,STRONG,7.126058e+07,0.931626,404976.670717,0.986234,98789
37,2021q2,MODERATE,4.443282e+06,0.058089,3072.258111,0.007482,5799
38,2021q2,WEAK,6.267125e+05,0.008193,2316.156394,0.005641,804
39,2021q2,OUT_OF_SUPPORT,1.599547e+05,0.002091,264.490651,0.000644,247
40,2021q3,STRONG,7.480458e+07,0.931677,419315.910037,0.983306,124675
41,2021q3,MODERATE,4.684356e+06,0.058343,3631.840918,0.008517,7276
42,2021q3,WEAK,6.352793e+05,0.007912,3310.165768,0.007762,1011
43,2021q3,OUT_OF_SUPPORT,1.660272e+05,0.002068,176.858229,0.000415,288
44,2021q4,STRONG,7.730717e+07,0.933485,447591.752850,0.990120,135483
45,2021q4,MODERATE,4.796752e+06,0.057921,3963.513083,0.008768,7767
46,2021q4,WEAK,5.493841e+05,0.006634,384.521447,0.000851,936
47,2021q4,OUT_OF_SUPPORT,1.623494e+05,0.001960,118.163697,0.000261,277

In [13]:
divergence = pd.read_csv(artifacts['divergence'])
divergence

,source_period,spearman_rank_correlation,mean_absolute_probability_difference,pooled_total,knn_total,relative_total_difference
0,2019q1,0.226806,0.001319,317478.603902,314333.518838,-0.009906
1,2019q2,0.240426,0.001322,322971.633478,325674.003459,0.008367
2,2019q3,0.222186,0.001354,342236.920247,345737.232383,0.010228
3,2019q4,0.218784,0.001402,358152.489032,363949.155934,0.016185
4,2020q1,0.219106,0.001391,355182.969437,356456.183066,0.003585
5,2020q2,0.230702,0.001317,352728.846651,354558.686477,0.005188
6,2020q3,0.232223,0.001478,360248.481674,374040.572151,0.038285
7,2020q4,0.239816,0.001282,358670.590713,366543.420161,0.021950
8,2021q1,0.248244,0.001279,383733.366363,390276.077415,0.017050
9,2021q2,0.241309,0.001360,410629.575872,420827.755891,0.024835
10,2021q3,0.230078,0.001368,426434.774952,434751.518867,0.019503
11,2021q4,0.218583,0.001420,452057.951077,460732.323879,0.019189

In [14]:
if lock['status'] == 'FINAL_CERTIFIED':
    FINAL_LOCK = ROOT / '00_admin' / 'PNADC_HISTORICAL_BACKCAST_FINAL_LOCK.json'
    final_lock = json.loads(FINAL_LOCK.read_text(encoding='utf-8'))
    print(json.dumps(final_lock, ensure_ascii=False, indent=2))
else:
    print('Hardening bloqueado. Examine critical_failures e o relatório antes de qualquer uso substantivo.')

{
  "freeze_id": "20260724T171145Z",
  "status": "FINAL_CERTIFIED",
  "component": "PNADC_HISTORICAL_BACKCAST",
  "hardening_lock": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/PNADC_HISTORICAL_BACKCAST_HARDENING_LOCK.json",
  "upstream_core_freeze": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/PNADC_HISTORICAL_PROXY_CORE_FREEZE.json",
  "final_estimates": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_backcast_hardening/pnadc_historical_backcast_final_estimates_20260724T171145Z.csv",
  "final_estimates_sha256": "2dd6c3377819afee2d78f637b3e1488767887a80a97004f474f3c47479b475da",
  "model_bundle": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_backcast_hardening/pnadc_historical_backcast_hardening_bundle_20260724T171145Z.joblib",
  "model_bundle_sha256": "42218fb582ce3b1d2cf6563b0944ccd8cbfebdc1ed4cd889506f2ceb93b8cb76",
  "read_only": true,
  "evidence_tier": "C",
  "direct_platform_observed_historical": false,
  "claim_ceiling": "Reconstrução retrospectiva probabilística agregada da compatibilidade histórica com entrega por plataforma, calibrada em 2022T4/2024T3, com incerteza e suporte explicitados.",
  "created_at_utc": "2026-07-24T17:17:02.399998+00:00"
}

In [15]:
import pandas as pd

mca = pd.read_csv(PATH_MCA_CELLS)
support = pd.read_csv(PATH_SUPPORT)

print(mca.shape, support.shape)
print(mca.columns.tolist())
print(support.columns.tolist())
print(mca.equals(support))

NameError: name 'PATH_MCA_CELLS' is not defined