# PNADc Historical Proxy Engine v1.0.1\nCorreção: seleção de layout regular separada do seletor dos suplementos diretos.\n

# SPINE-GPE v7 — PNADc Historical Certification & Proxy Calibration Engine v1.0.1

Este notebook executa a auditoria, a calibração temporal 2022T4/2024T3 e a certificação das fontes regulares da PNADc já disponíveis no Drive.

**Limite obrigatório:** a série histórica recebe probabilidade modelada (`evidence tier C`); `platform_delivery_direct` permanece ausente.

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
from pathlib import Path
import json
import subprocess
import sys

ROOT = Path('/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7')
SCRIPT = ROOT / 'scripts/SPINE_GPEv7_PNADC_HISTORICAL_PROXY_ENGINE_v1.0.1.py'
REQ = ROOT / 'scripts/requirements_SPINE_GPEv7_PNADC_HISTORICAL_PROXY_ENGINE_v1.0.1.txt'
UPSTREAM = ROOT / 'scripts/SPINE_GPEv7_PNADC_CERTIFIER_v1.2.0.py'

print('ROOT:', ROOT)
print('SCRIPT:', SCRIPT, SCRIPT.exists())
print('REQ:', REQ, REQ.exists())
print('UPSTREAM:', UPSTREAM, UPSTREAM.exists())
assert SCRIPT.exists()
assert REQ.exists()
assert UPSTREAM.exists()

ROOT: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7
SCRIPT: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/scripts/SPINE_GPEv7_PNADC_HISTORICAL_PROXY_ENGINE_v1.0.1.py True
REQ: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/scripts/requirements_SPINE_GPEv7_PNADC_HISTORICAL_PROXY_ENGINE_v1.0.1.txt True
UPSTREAM: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/scripts/SPINE_GPEv7_PNADC_CERTIFIER_v1.2.0.py True

In [7]:
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '-r', str(REQ)], check=True)
subprocess.run([sys.executable, '-m', 'py_compile', str(SCRIPT)], check=True)
print('py_compile: OK')

py_compile: OK

## 1. Auditoria das fontes locais

O modo `auto` descobre os trimestres já materializados em `data_pnadc` e `01_raw/10_ibge/pnadc_historical`, excluindo os módulos especiais diretos.

In [8]:
audit = subprocess.run(
    [
        sys.executable, str(SCRIPT),
        '--root', str(ROOT),
        '--mode', 'audit',
        '--periods', 'auto',
        '--strict',
    ],
    text=True,
    capture_output=True,
    check=False,
)
print(audit.stdout)
print(audit.stderr)
print('Audit exit code:', audit.returncode)

2026-07-23 12:30:16,271 | INFO | SPINE-GPE PNADc Historical Proxy Engine v1.0.1 | root=/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7 | mode=audit | periods=auto
2026-07-23 12:35:47,502 | INFO | Auditoria concluída | status=AUDIT_PASSED | períodos=['2019q1', '2019q2', '2019q3', '2019q4', '2020q1', '2020q2', '2020q3', '2020q4', '2021q1', '2021q2', '2021q3', '2021q4', '2022q4', '2024q3']
{
  "run_id": "20260723T123016Z",
  "script_version": "1.0.1",
  "validation_schema_version": "spine-gpe-v7-pnadc-historical-validation-1.0.1",
  "mode": "audit",
  "status": "AUDIT_PASSED",
  "critical_failures": [],
  "warnings": [],
  "requested_periods": [
    "2019q1",
    "2019q2",
    "2019q3",
    "2019q4",
    "2020q1",
    "2020q2",
    "2020q3",
    "2020q4",
    "2021q1",
    "2021q2",
    "2021q3",
    "2021q4",
    "2022q4",
    "2024q3"
  ],
  "sources": [
    {
      "period": "2019q1",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2019q1/PNADC_012019.txt",
      "suffix": ".txt",
      "sha256": "ac864079cd089a770c756b01f89a606a8e56803b99f656ddf046b67f9e477f3d",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2019q2",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2019q2/PNADC_022019.txt",
      "suffix": ".txt",
      "sha256": "f676b76178f176c32ef4cfc6abef7dc464fc5811c29dd0534a3032c2695392c0",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2019q3",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2019q3/PNADC_032019.txt",
      "suffix": ".txt",
      "sha256": "d310562dad7931af16a7498a779365a487b17e79ba60163c68de7e88c5dd464f",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2019q4",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2019q4/PNADC_042019.txt",
      "suffix": ".txt",
      "sha256": "223bf7c62fabe7da3497cb0089969278184656da0d8cce94aba2385b9f8d5727",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2020q1",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2020q1/PNADC_012020.txt",
      "suffix": ".txt",
      "sha256": "7eadcc3a35d5d14a9e20ca1b181680376af6b59ba15a6c016262e00af5f52fc2",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2020q2",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2020q2/PNADC_022020.txt",
      "suffix": ".txt",
      "sha256": "6af767ffac2ead64ec9a1d907a1b9b563be0e75d167de11113ab9431075303ed",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2020q3",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2020q3/PNADC_032020.txt",
      "suffix": ".txt",
      "sha256": "651aa4aff81a87684341b34d0d9eb44869fa09fed7061e48cf3a8f8e32faed9b",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2020q4",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2020q4/PNADC_042020.txt",
      "suffix": ".txt",
      "sha256": "2ccb73d9bca8326f151304612dac0da58f311f65569e3c70731fc593f70bcc02",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2021q1",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2021q1/PNADC_012021.txt",
      "suffix": ".txt",
      "sha256": "25000f70e0bd3d7ea216577ce2dfc8b30e03fed04278e933589e1b23c97c2ee7",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2021q2",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2021q2/PNADC_022021.txt",
      "suffix": ".txt",
      "sha256": "3409d1aa4796392e9f7a948cff9e112698e05bc9bf4eec7c7fe019163f30789f",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2021q3",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2021q3/PNADC_032021.txt",
      "suffix": ".txt",
      "sha256": "1ca01c29535d175e71f4e7e53739cdce9db3a9241e26460b42633c3b209a2add",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2021q4",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2021q4/PNADC_042021.txt",
      "suffix": ".txt",
      "sha256": "44f637e19fadfb61e40f826555052432497f445a14a06b04071fc1fdadb95428",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2022q4",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/data_pnadc/PNADC_042022.txt",
      "suffix": ".txt",
      "sha256": "4ae10a8879be31c0344f135aed645be87b0c0466538986093e0303c96485b6ab",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2024q3",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/data_pnadc/PNADC_032024.txt",
      "suffix": ".txt",
      "sha256": "9dbf8aece9cf959c56ec218f360d4b138923574f0102981bbaa2f0b85564e36f",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    }
  ],
  "direct_parquets": {
    "2022": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/10_pnadc_certified/certified_pnadc_platform_2022.parquet",
    "2024": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/10_pnadc_certified/certified_pnadc_platform_2024.parquet"
  },
  "upstream_parser": {
    "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/scripts/SPINE_GPEv7_PNADC_CERTIFIER_v1.2.0.py",
    "sha256": "e46d2e65ce0f49810d8dc0c72771ab93df984660ff3970a781ec9628e4f6e3cf"
  },
  "created_at_utc": "2026-07-23T12:35:47.481839+00:00"
}


Audit exit code: 0

In [9]:
AUDIT_LOCK = ROOT / '00_admin/PNADC_HISTORICAL_PROXY_AUDIT_LOCK.json'
if not AUDIT_LOCK.exists():
    raise RuntimeError('Lock de auditoria não foi criado. Revise STDOUT/STDERR.')
audit_lock = json.loads(AUDIT_LOCK.read_text(encoding='utf-8'))
print(json.dumps(audit_lock, ensure_ascii=False, indent=2))
assert audit_lock['status'] == 'AUDIT_PASSED', audit_lock['critical_failures']
print('Períodos descobertos:', audit_lock['requested_periods'])

{
  "run_id": "20260723T123016Z",
  "script_version": "1.0.1",
  "validation_schema_version": "spine-gpe-v7-pnadc-historical-validation-1.0.1",
  "mode": "audit",
  "status": "AUDIT_PASSED",
  "critical_failures": [],
  "warnings": [],
  "requested_periods": [
    "2019q1",
    "2019q2",
    "2019q3",
    "2019q4",
    "2020q1",
    "2020q2",
    "2020q3",
    "2020q4",
    "2021q1",
    "2021q2",
    "2021q3",
    "2021q4",
    "2022q4",
    "2024q3"
  ],
  "sources": [
    {
      "period": "2019q1",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2019q1/PNADC_012019.txt",
      "suffix": ".txt",
      "sha256": "ac864079cd089a770c756b01f89a606a8e56803b99f656ddf046b67f9e477f3d",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2019q2",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2019q2/PNADC_022019.txt",
      "suffix": ".txt",
      "sha256": "f676b76178f176c32ef4cfc6abef7dc464fc5811c29dd0534a3032c2695392c0",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2019q3",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2019q3/PNADC_032019.txt",
      "suffix": ".txt",
      "sha256": "d310562dad7931af16a7498a779365a487b17e79ba60163c68de7e88c5dd464f",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2019q4",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2019q4/PNADC_042019.txt",
      "suffix": ".txt",
      "sha256": "223bf7c62fabe7da3497cb0089969278184656da0d8cce94aba2385b9f8d5727",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2020q1",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2020q1/PNADC_012020.txt",
      "suffix": ".txt",
      "sha256": "7eadcc3a35d5d14a9e20ca1b181680376af6b59ba15a6c016262e00af5f52fc2",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2020q2",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2020q2/PNADC_022020.txt",
      "suffix": ".txt",
      "sha256": "6af767ffac2ead64ec9a1d907a1b9b563be0e75d167de11113ab9431075303ed",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2020q3",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2020q3/PNADC_032020.txt",
      "suffix": ".txt",
      "sha256": "651aa4aff81a87684341b34d0d9eb44869fa09fed7061e48cf3a8f8e32faed9b",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2020q4",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2020q4/PNADC_042020.txt",
      "suffix": ".txt",
      "sha256": "2ccb73d9bca8326f151304612dac0da58f311f65569e3c70731fc593f70bcc02",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2021q1",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2021q1/PNADC_012021.txt",
      "suffix": ".txt",
      "sha256": "25000f70e0bd3d7ea216577ce2dfc8b30e03fed04278e933589e1b23c97c2ee7",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2021q2",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2021q2/PNADC_022021.txt",
      "suffix": ".txt",
      "sha256": "3409d1aa4796392e9f7a948cff9e112698e05bc9bf4eec7c7fe019163f30789f",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2021q3",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2021q3/PNADC_032021.txt",
      "suffix": ".txt",
      "sha256": "1ca01c29535d175e71f4e7e53739cdce9db3a9241e26460b42633c3b209a2add",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2021q4",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/01_raw/10_ibge/pnadc_historical/2021q4/PNADC_042021.txt",
      "suffix": ".txt",
      "sha256": "44f637e19fadfb61e40f826555052432497f445a14a06b04071fc1fdadb95428",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2022q4",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/data_pnadc/PNADC_042022.txt",
      "suffix": ".txt",
      "sha256": "4ae10a8879be31c0344f135aed645be87b0c0466538986093e0303c96485b6ab",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    },
    {
      "period": "2024q3",
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/data_pnadc/PNADC_032024.txt",
      "suffix": ".txt",
      "sha256": "9dbf8aece9cf959c56ec218f360d4b138923574f0102981bbaa2f0b85564e36f",
      "record_width": 3478,
      "layout_path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/02_interim/10_pnadc_certification/extracted_docs/Dicionario_e_input_20221031/dicionario_PNADC_microdados_trimestral.xls",
      "layout_sha256": "3f6b46ea00fd1549b52f878e3834135b6b2ae71a09ed576c458330e522e80eda",
      "layout_width": 3478,
      "source_kind": "regular_quarterly"
    }
  ],
  "direct_parquets": {
    "2022": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/10_pnadc_certified/certified_pnadc_platform_2022.parquet",
    "2024": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/10_pnadc_certified/certified_pnadc_platform_2024.parquet"
  },
  "upstream_parser": {
    "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/scripts/SPINE_GPEv7_PNADC_CERTIFIER_v1.2.0.py",
    "sha256": "e46d2e65ce0f49810d8dc0c72771ab93df984660ff3970a781ec9628e4f6e3cf"
  },
  "created_at_utc": "2026-07-23T12:35:47.481839+00:00"
}
Períodos descobertos: ['2019q1', '2019q2', '2019q3', '2019q4', '2020q1', '2020q2', '2020q3', '2020q4', '2021q1', '2021q2', '2021q3', '2021q4', '2022q4', '2024q3']

## 2. Calibração e certificação

Esta etapa:

1. lê os Parquets diretos certificados de 2022 e 2024;
2. valida temporalmente o modelo nos dois sentidos;
3. calibra a probabilidade;
4. aplica o modelo apenas aos trimestres regulares descobertos;
5. gera outputs imutáveis, model card, estimativas, lock e freeze.

In [10]:
full = subprocess.run(
    [
        sys.executable, str(SCRIPT),
        '--root', str(ROOT),
        '--mode', 'full',
        '--periods', 'auto',
        '--chunk-rows', '50000',
        '--strict',
    ],
    text=True,
    capture_output=True,
    check=False,
)
print(full.stdout)
print(full.stderr)
print('Full exit code:', full.returncode)

2026-07-23 12:40:00,706 | INFO | SPINE-GPE PNADc Historical Proxy Engine v1.0.1 | root=/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7 | mode=full | periods=auto
2026-07-23 12:41:50,022 | INFO | 2019q1: 50000 registros brutos lidos; 16621 no universo histórico
2026-07-23 12:41:59,394 | INFO | 2019q1: 100000 registros brutos lidos; 30984 no universo histórico
2026-07-23 12:42:06,636 | INFO | 2019q1: 150000 registros brutos lidos; 46059 no universo histórico
2026-07-23 12:42:16,184 | INFO | 2019q1: 200000 registros brutos lidos; 61493 no universo histórico
2026-07-23 12:42:23,417 | INFO | 2019q1: 250000 registros brutos lidos; 75789 no universo histórico
2026-07-23 12:42:32,997 | INFO | 2019q1: 300000 registros brutos lidos; 94937 no universo histórico
2026-07-23 12:42:41,929 | INFO | 2019q1: 350000 registros brutos lidos; 114775 no universo histórico
2026-07-23 12:42:50,403 | INFO | 2019q1: 400000 registros brutos lidos; 135682 no universo histórico
2026-07-23 12:43:00,176 | INFO | 2019q1: 450000 registros brutos lidos; 157343 no universo histórico
2026-07-23 12:43:07,817 | INFO | 2019q1: 500000 registros brutos lidos; 179506 no universo histórico
2026-07-23 12:43:17,569 | INFO | 2019q1: 550000 registros brutos lidos; 200210 no universo histórico
2026-07-23 12:43:18,252 | INFO | 2019q1: 553308 registros brutos lidos; 201434 no universo histórico
2026-07-23 12:44:15,474 | INFO | 2019q2: 50000 registros brutos lidos; 16885 no universo histórico
2026-07-23 12:44:22,905 | INFO | 2019q2: 100000 registros brutos lidos; 31744 no universo histórico
2026-07-23 12:44:32,411 | INFO | 2019q2: 150000 registros brutos lidos; 46907 no universo histórico
2026-07-23 12:44:40,234 | INFO | 2019q2: 200000 registros brutos lidos; 62224 no universo histórico
2026-07-23 12:44:49,309 | INFO | 2019q2: 250000 registros brutos lidos; 76835 no universo histórico
2026-07-23 12:45:00,227 | INFO | 2019q2: 300000 registros brutos lidos; 96553 no universo histórico
2026-07-23 12:45:07,918 | INFO | 2019q2: 350000 registros brutos lidos; 116652 no universo histórico
2026-07-23 12:45:17,685 | INFO | 2019q2: 400000 registros brutos lidos; 137804 no universo histórico
2026-07-23 12:45:26,471 | INFO | 2019q2: 450000 registros brutos lidos; 159681 no universo histórico
2026-07-23 12:45:35,185 | INFO | 2019q2: 500000 registros brutos lidos; 181881 no universo histórico
2026-07-23 12:45:45,027 | INFO | 2019q2: 550000 registros brutos lidos; 202681 no universo histórico
2026-07-23 12:45:45,410 | INFO | 2019q2: 551348 registros brutos lidos; 203203 no universo histórico
2026-07-23 12:46:34,306 | INFO | 2019q3: 50000 registros brutos lidos; 16850 no universo histórico
2026-07-23 12:46:43,107 | INFO | 2019q3: 100000 registros brutos lidos; 31790 no universo histórico
2026-07-23 12:46:51,309 | INFO | 2019q3: 150000 registros brutos lidos; 47131 no universo histórico
2026-07-23 12:47:00,948 | INFO | 2019q3: 200000 registros brutos lidos; 62532 no universo histórico
2026-07-23 12:47:08,305 | INFO | 2019q3: 250000 registros brutos lidos; 77015 no universo histórico
2026-07-23 12:47:18,170 | INFO | 2019q3: 300000 registros brutos lidos; 96548 no universo histórico
2026-07-23 12:47:26,344 | INFO | 2019q3: 350000 registros brutos lidos; 116456 no universo histórico
2026-07-23 12:47:35,479 | INFO | 2019q3: 400000 registros brutos lidos; 137762 no universo histórico
2026-07-23 12:47:45,433 | INFO | 2019q3: 450000 registros brutos lidos; 159589 no universo histórico
2026-07-23 12:47:53,353 | INFO | 2019q3: 500000 registros brutos lidos; 181582 no universo histórico
2026-07-23 12:48:03,257 | INFO | 2019q3: 550000 registros brutos lidos; 202594 no universo histórico
2026-07-23 12:48:03,488 | INFO | 2019q3: 550227 registros brutos lidos; 202679 no universo histórico
2026-07-23 12:48:54,474 | INFO | 2019q4: 50000 registros brutos lidos; 16927 no universo histórico
2026-07-23 12:49:03,995 | INFO | 2019q4: 100000 registros brutos lidos; 31696 no universo histórico
2026-07-23 12:49:12,520 | INFO | 2019q4: 150000 registros brutos lidos; 47531 no universo histórico
2026-07-23 12:49:20,919 | INFO | 2019q4: 200000 registros brutos lidos; 62845 no universo histórico
2026-07-23 12:49:30,374 | INFO | 2019q4: 250000 registros brutos lidos; 77484 no universo histórico
2026-07-23 12:49:37,926 | INFO | 2019q4: 300000 registros brutos lidos; 97591 no universo histórico
2026-07-23 12:49:47,703 | INFO | 2019q4: 350000 registros brutos lidos; 117205 no universo histórico
2026-07-23 12:49:56,700 | INFO | 2019q4: 400000 registros brutos lidos; 139039 no universo histórico
2026-07-23 12:50:05,566 | INFO | 2019q4: 450000 registros brutos lidos; 161215 no universo histórico
2026-07-23 12:50:15,373 | INFO | 2019q4: 500000 registros brutos lidos; 183333 no universo histórico
2026-07-23 12:50:21,960 | INFO | 2019q4: 542802 registros brutos lidos; 201237 no universo histórico
2026-07-23 12:51:25,113 | INFO | 2020q1: 50000 registros brutos lidos; 16635 no universo histórico
2026-07-23 12:51:34,429 | INFO | 2020q1: 100000 registros brutos lidos; 30258 no universo histórico
2026-07-23 12:51:42,504 | INFO | 2020q1: 150000 registros brutos lidos; 45946 no universo histórico
2026-07-23 12:51:52,315 | INFO | 2020q1: 200000 registros brutos lidos; 59775 no universo histórico
2026-07-23 12:52:00,360 | INFO | 2020q1: 250000 registros brutos lidos; 77623 no universo histórico
2026-07-23 12:52:10,516 | INFO | 2020q1: 300000 registros brutos lidos; 97628 no universo histórico
2026-07-23 12:52:21,488 | INFO | 2020q1: 350000 registros brutos lidos; 118162 no universo histórico
2026-07-23 12:52:30,786 | INFO | 2020q1: 400000 registros brutos lidos; 140006 no universo histórico
2026-07-23 12:52:40,890 | INFO | 2020q1: 450000 registros brutos lidos; 161690 no universo histórico
2026-07-23 12:52:47,022 | INFO | 2020q1: 487937 registros brutos lidos; 177234 no universo histórico
2026-07-23 12:53:29,217 | INFO | 2020q2: 50000 registros brutos lidos; 14497 no universo histórico
2026-07-23 12:53:38,659 | INFO | 2020q2: 100000 registros brutos lidos; 26572 no universo histórico
2026-07-23 12:53:45,992 | INFO | 2020q2: 150000 registros brutos lidos; 38564 no universo histórico
2026-07-23 12:53:56,330 | INFO | 2020q2: 200000 registros brutos lidos; 55457 no universo histórico
2026-07-23 12:54:04,543 | INFO | 2020q2: 250000 registros brutos lidos; 72909 no universo histórico
2026-07-23 12:54:13,643 | INFO | 2020q2: 300000 registros brutos lidos; 93130 no universo histórico
2026-07-23 12:54:23,510 | INFO | 2020q2: 350000 registros brutos lidos; 113002 no universo histórico
2026-07-23 12:54:26,587 | INFO | 2020q2: 369156 registros brutos lidos; 119921 no universo histórico
2026-07-23 12:55:06,475 | INFO | 2020q3: 50000 registros brutos lidos; 14874 no universo histórico
2026-07-23 12:55:14,463 | INFO | 2020q3: 100000 registros brutos lidos; 26929 no universo histórico
2026-07-23 12:55:23,948 | INFO | 2020q3: 150000 registros brutos lidos; 38590 no universo histórico
2026-07-23 12:55:31,426 | INFO | 2020q3: 200000 registros brutos lidos; 54781 no universo histórico
2026-07-23 12:55:41,178 | INFO | 2020q3: 250000 registros brutos lidos; 71939 no universo histórico
2026-07-23 12:55:49,383 | INFO | 2020q3: 300000 registros brutos lidos; 91532 no universo histórico
2026-07-23 12:55:59,206 | INFO | 2020q3: 350000 registros brutos lidos; 111158 no universo histórico
2026-07-23 12:56:02,154 | INFO | 2020q3: 368210 registros brutos lidos; 117589 no universo histórico
2026-07-23 12:56:44,133 | INFO | 2020q4: 50000 registros brutos lidos; 15412 no universo histórico
2026-07-23 12:56:53,427 | INFO | 2020q4: 100000 registros brutos lidos; 28430 no universo histórico
2026-07-23 12:57:00,821 | INFO | 2020q4: 150000 registros brutos lidos; 41868 no universo histórico
2026-07-23 12:57:10,678 | INFO | 2020q4: 200000 registros brutos lidos; 60114 no universo histórico
2026-07-23 12:57:18,467 | INFO | 2020q4: 250000 registros brutos lidos; 78200 no universo histórico
2026-07-23 12:57:28,495 | INFO | 2020q4: 300000 registros brutos lidos; 98677 no universo histórico
2026-07-23 12:57:34,150 | INFO | 2020q4: 335566 registros brutos lidos; 112149 no universo histórico
2026-07-23 12:58:18,390 | INFO | 2021q1: 50000 registros brutos lidos; 15296 no universo histórico
2026-07-23 12:58:27,500 | INFO | 2021q1: 100000 registros brutos lidos; 28118 no universo histórico
2026-07-23 12:58:36,460 | INFO | 2021q1: 150000 registros brutos lidos; 41569 no universo histórico
2026-07-23 12:58:44,877 | INFO | 2021q1: 200000 registros brutos lidos; 60182 no universo histórico
2026-07-23 12:58:54,961 | INFO | 2021q1: 250000 registros brutos lidos; 79177 no universo histórico
2026-07-23 12:59:02,705 | INFO | 2021q1: 300000 registros brutos lidos; 99508 no universo histórico
2026-07-23 12:59:08,154 | INFO | 2021q1: 319898 registros brutos lidos; 106865 no universo histórico
2026-07-23 12:59:47,700 | INFO | 2021q2: 50000 registros brutos lidos; 15967 no universo histórico
2026-07-23 12:59:57,120 | INFO | 2021q2: 100000 registros brutos lidos; 29082 no universo histórico
2026-07-23 13:00:05,554 | INFO | 2021q2: 150000 registros brutos lidos; 42562 no universo histórico
2026-07-23 13:00:14,672 | INFO | 2021q2: 200000 registros brutos lidos; 60476 no universo histórico
2026-07-23 13:00:24,418 | INFO | 2021q2: 250000 registros brutos lidos; 79270 no universo histórico
2026-07-23 13:00:32,131 | INFO | 2021q2: 300000 registros brutos lidos; 100072 no universo histórico
2026-07-23 13:00:42,037 | INFO | 2021q2: 350000 registros brutos lidos; 119975 no universo histórico
2026-07-23 13:00:43,182 | INFO | 2021q2: 356239 registros brutos lidos; 122229 no universo histórico
2026-07-23 13:01:37,967 | INFO | 2021q3: 50000 registros brutos lidos; 17090 no universo histórico
2026-07-23 13:01:47,733 | INFO | 2021q3: 100000 registros brutos lidos; 30914 no universo histórico
2026-07-23 13:01:55,117 | INFO | 2021q3: 150000 registros brutos lidos; 45465 no universo histórico
2026-07-23 13:02:05,066 | INFO | 2021q3: 200000 registros brutos lidos; 60138 no universo histórico
2026-07-23 13:02:13,788 | INFO | 2021q3: 250000 registros brutos lidos; 79777 no universo histórico
2026-07-23 13:02:22,775 | INFO | 2021q3: 300000 registros brutos lidos; 99134 no universo histórico
2026-07-23 13:02:32,710 | INFO | 2021q3: 350000 registros brutos lidos; 120428 no universo histórico
2026-07-23 13:02:40,343 | INFO | 2021q3: 400000 registros brutos lidos; 141626 no universo histórico
2026-07-23 13:02:48,115 | INFO | 2021q3: 434822 registros brutos lidos; 155713 no universo histórico
2026-07-23 13:03:39,773 | INFO | 2021q4: 50000 registros brutos lidos; 17057 no universo histórico
2026-07-23 13:03:49,288 | INFO | 2021q4: 100000 registros brutos lidos; 31186 no universo histórico
2026-07-23 13:03:56,643 | INFO | 2021q4: 150000 registros brutos lidos; 45940 no universo histórico
2026-07-23 13:04:06,668 | INFO | 2021q4: 200000 registros brutos lidos; 60751 no universo histórico
2026-07-23 13:04:15,872 | INFO | 2021q4: 250000 registros brutos lidos; 79597 no universo histórico
2026-07-23 13:04:24,364 | INFO | 2021q4: 300000 registros brutos lidos; 98942 no universo histórico
2026-07-23 13:04:34,273 | INFO | 2021q4: 350000 registros brutos lidos; 120708 no universo histórico
2026-07-23 13:04:41,970 | INFO | 2021q4: 400000 registros brutos lidos; 142887 no universo histórico
2026-07-23 13:04:51,673 | INFO | 2021q4: 450000 registros brutos lidos; 163989 no universo histórico
2026-07-23 13:04:53,685 | INFO | 2021q4: 461795 registros brutos lidos; 168659 no universo histórico
2026-07-23 13:05:48,143 | INFO | 2022q4: 50000 registros brutos lidos; 16916 no universo histórico
2026-07-23 13:05:55,555 | INFO | 2022q4: 100000 registros brutos lidos; 32003 no universo histórico
2026-07-23 13:06:05,964 | INFO | 2022q4: 150000 registros brutos lidos; 47361 no universo histórico
2026-07-23 13:06:13,232 | INFO | 2022q4: 200000 registros brutos lidos; 62280 no universo histórico
2026-07-23 13:06:22,906 | INFO | 2022q4: 250000 registros brutos lidos; 80351 no universo histórico
2026-07-23 13:06:31,765 | INFO | 2022q4: 300000 registros brutos lidos; 100296 no universo histórico
2026-07-23 13:06:40,398 | INFO | 2022q4: 350000 registros brutos lidos; 121877 no universo histórico
2026-07-23 13:06:50,219 | INFO | 2022q4: 400000 registros brutos lidos; 144150 no universo histórico
2026-07-23 13:06:57,840 | INFO | 2022q4: 450000 registros brutos lidos; 166318 no universo histórico
2026-07-23 13:07:04,493 | INFO | 2022q4: 478091 registros brutos lidos; 178163 no universo histórico
2026-07-23 13:07:54,338 | INFO | 2024q3: 50000 registros brutos lidos; 17376 no universo histórico
2026-07-23 13:08:02,844 | INFO | 2024q3: 100000 registros brutos lidos; 32825 no universo histórico
2026-07-23 13:08:11,835 | INFO | 2024q3: 150000 registros brutos lidos; 48528 no universo histórico
2026-07-23 13:08:21,495 | INFO | 2024q3: 200000 registros brutos lidos; 64062 no universo histórico
2026-07-23 13:08:29,047 | INFO | 2024q3: 250000 registros brutos lidos; 83046 no universo histórico
2026-07-23 13:08:38,893 | INFO | 2024q3: 300000 registros brutos lidos; 103494 no universo histórico
2026-07-23 13:08:47,679 | INFO | 2024q3: 350000 registros brutos lidos; 125758 no universo histórico
2026-07-23 13:08:56,663 | INFO | 2024q3: 400000 registros brutos lidos; 148859 no universo histórico
2026-07-23 13:09:06,854 | INFO | 2024q3: 450000 registros brutos lidos; 171271 no universo histórico
2026-07-23 13:09:11,661 | INFO | 2024q3: 479778 registros brutos lidos; 184157 no universo histórico
2026-07-23 13:09:24,552 | INFO | PNADc histórica concluída | status=CERTIFIED | períodos=['2019q1', '2019q2', '2019q3', '2019q4', '2020q1', '2020q2', '2020q3', '2020q4', '2021q1', '2021q2', '2021q3', '2021q4', '2022q4', '2024q3']
{
  "run_id": "20260723T124000Z",
  "script_version": "1.0.1",
  "schema_version": "spine-gpe-v7-pnadc-historical-proxy-1.0.0",
  "validation_schema_version": "spine-gpe-v7-pnadc-historical-validation-1.0.1",
  "model_schema_version": "spine-gpe-v7-pnadc-proxy-model-1.0.0",
  "mode": "full",
  "status": "CERTIFIED",
  "critical_failures": [],
  "warnings": [],
  "requested_periods": [
    "2019q1",
    "2019q2",
    "2019q3",
    "2019q4",
    "2020q1",
    "2020q2",
    "2020q3",
    "2020q4",
    "2021q1",
    "2021q2",
    "2021q3",
    "2021q4",
    "2022q4",
    "2024q3"
  ],
  "certified_periods": [
    "2019q1",
    "2019q2",
    "2019q3",
    "2019q4",
    "2020q1",
    "2020q2",
    "2020q3",
    "2020q4",
    "2021q1",
    "2021q2",
    "2021q3",
    "2021q4",
    "2022q4",
    "2024q3"
  ],
  "direct_inputs": {
    "2022": {
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/10_pnadc_certified/certified_pnadc_platform_2022.parquet",
      "sha256": "30dcfee62e19b17eb6a2e0526f3100424a60a3a3f7877870bdf1d1a081e876e2"
    },
    "2024": {
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/10_pnadc_certified/certified_pnadc_platform_2024.parquet",
      "sha256": "0b228eeeb55653a9ebca54a4c5e9003af7be2ac7953a78241dc14d75ce18297c"
    }
  },
  "upstream_parser": {
    "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/scripts/SPINE_GPEv7_PNADC_CERTIFIER_v1.2.0.py",
    "version": "1.2.0",
    "sha256": "e46d2e65ce0f49810d8dc0c72771ab93df984660ff3970a781ec9628e4f6e3cf"
  },
  "model": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_proxy/pnadc_historical_proxy_model_20260723T124000Z.joblib",
  "model_card": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_proxy/pnadc_historical_proxy_model_card_20260723T124000Z.md",
  "model_threshold_diagnostic": 0.22,
  "primary_features": [
    "occupation_code",
    "activity_code",
    "position_code"
  ],
  "historical_outputs": {
    "2019q1": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2019q1_20260723T124000Z.parquet",
    "2019q2": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2019q2_20260723T124000Z.parquet",
    "2019q3": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2019q3_20260723T124000Z.parquet",
    "2019q4": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2019q4_20260723T124000Z.parquet",
    "2020q1": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2020q1_20260723T124000Z.parquet",
    "2020q2": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2020q2_20260723T124000Z.parquet",
    "2020q3": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2020q3_20260723T124000Z.parquet",
    "2020q4": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2020q4_20260723T124000Z.parquet",
    "2021q1": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2021q1_20260723T124000Z.parquet",
    "2021q2": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2021q2_20260723T124000Z.parquet",
    "2021q3": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2021q3_20260723T124000Z.parquet",
    "2021q4": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2021q4_20260723T124000Z.parquet",
    "2022q4": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2022q4_20260723T124000Z.parquet",
    "2024q3": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2024q3_20260723T124000Z.parquet"
  },
  "manifests": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/registry/pnadc_historical_proxy_manifests_20260723T124000Z.json",
  "estimates": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_proxy/pnadc_historical_proxy_estimates_20260723T124000Z.csv",
  "report": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_proxy/pnadc_historical_proxy_report_20260723T124000Z.md",
  "artifact_hashes": {
    "report": "68816d9a482940ab6fdb917d6682a90545a2a28209663b176cb7091775afbb94",
    "manifests": "92f64016ef43431ba329d75679b2860f14c74a3bcaa486fe93c789ce926a6244",
    "estimates": "de9f2a75f03723d9696187b696ad14a7b250b6a5c4072e9ef39cbba377e6612c",
    "upstream_parser": "e46d2e65ce0f49810d8dc0c72771ab93df984660ff3970a781ec9628e4f6e3cf",
    "model": "c4f43877e7379a11a503151a275a256f3dc1bb36c749b9f84cf695c5e9723237",
    "model_card": "8a1c47b8ff265ba3cda2082ae785264451164b01e2c54835f5957dd4a3a8e849"
  },
  "epistemic_limit": "Probabilidade histórica modelada; plataforma direta permanece não observada fora dos módulos especiais.",
  "claim_ceiling": "Estimativa model-based agregada de compatibilidade histórica com entrega por plataforma, calibrada em 2022T4/2024T3.",
  "created_at_utc": "2026-07-23T13:09:24.473280+00:00"
}


Full exit code: 0

In [11]:
LOCK = ROOT / '00_admin/PNADC_HISTORICAL_PROXY_CERTIFICATION_LOCK.json'
if not LOCK.exists():
    raise RuntimeError('Lock de certificação não foi criado. Revise STDOUT/STDERR.')
lock = json.loads(LOCK.read_text(encoding='utf-8'))
print(json.dumps(lock, ensure_ascii=False, indent=2))
assert lock['status'] == 'CERTIFIED', lock['critical_failures']
print('STATUS:', lock['status'])
print('MODELO:', lock['model'])
print('PERÍODOS:', lock['certified_periods'])
print('REPORT:', lock['report'])

{
  "run_id": "20260723T124000Z",
  "script_version": "1.0.1",
  "schema_version": "spine-gpe-v7-pnadc-historical-proxy-1.0.0",
  "validation_schema_version": "spine-gpe-v7-pnadc-historical-validation-1.0.1",
  "model_schema_version": "spine-gpe-v7-pnadc-proxy-model-1.0.0",
  "mode": "full",
  "status": "CERTIFIED",
  "critical_failures": [],
  "warnings": [],
  "requested_periods": [
    "2019q1",
    "2019q2",
    "2019q3",
    "2019q4",
    "2020q1",
    "2020q2",
    "2020q3",
    "2020q4",
    "2021q1",
    "2021q2",
    "2021q3",
    "2021q4",
    "2022q4",
    "2024q3"
  ],
  "certified_periods": [
    "2019q1",
    "2019q2",
    "2019q3",
    "2019q4",
    "2020q1",
    "2020q2",
    "2020q3",
    "2020q4",
    "2021q1",
    "2021q2",
    "2021q3",
    "2021q4",
    "2022q4",
    "2024q3"
  ],
  "direct_inputs": {
    "2022": {
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/10_pnadc_certified/certified_pnadc_platform_2022.parquet",
      "sha256": "30dcfee62e19b17eb6a2e0526f3100424a60a3a3f7877870bdf1d1a081e876e2"
    },
    "2024": {
      "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/10_pnadc_certified/certified_pnadc_platform_2024.parquet",
      "sha256": "0b228eeeb55653a9ebca54a4c5e9003af7be2ac7953a78241dc14d75ce18297c"
    }
  },
  "upstream_parser": {
    "path": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/scripts/SPINE_GPEv7_PNADC_CERTIFIER_v1.2.0.py",
    "version": "1.2.0",
    "sha256": "e46d2e65ce0f49810d8dc0c72771ab93df984660ff3970a781ec9628e4f6e3cf"
  },
  "model": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_proxy/pnadc_historical_proxy_model_20260723T124000Z.joblib",
  "model_card": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_proxy/pnadc_historical_proxy_model_card_20260723T124000Z.md",
  "model_threshold_diagnostic": 0.22,
  "primary_features": [
    "occupation_code",
    "activity_code",
    "position_code"
  ],
  "historical_outputs": {
    "2019q1": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2019q1_20260723T124000Z.parquet",
    "2019q2": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2019q2_20260723T124000Z.parquet",
    "2019q3": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2019q3_20260723T124000Z.parquet",
    "2019q4": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2019q4_20260723T124000Z.parquet",
    "2020q1": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2020q1_20260723T124000Z.parquet",
    "2020q2": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2020q2_20260723T124000Z.parquet",
    "2020q3": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2020q3_20260723T124000Z.parquet",
    "2020q4": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2020q4_20260723T124000Z.parquet",
    "2021q1": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2021q1_20260723T124000Z.parquet",
    "2021q2": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2021q2_20260723T124000Z.parquet",
    "2021q3": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2021q3_20260723T124000Z.parquet",
    "2021q4": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2021q4_20260723T124000Z.parquet",
    "2022q4": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2022q4_20260723T124000Z.parquet",
    "2024q3": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/03_processed/30_pnadc_historical_proxy/certified_pnadc_historical_proxy_2024q3_20260723T124000Z.parquet"
  },
  "manifests": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/00_admin/registry/pnadc_historical_proxy_manifests_20260723T124000Z.json",
  "estimates": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/tables/pnadc_historical_proxy/pnadc_historical_proxy_estimates_20260723T124000Z.csv",
  "report": "/content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_proxy/pnadc_historical_proxy_report_20260723T124000Z.md",
  "artifact_hashes": {
    "report": "68816d9a482940ab6fdb917d6682a90545a2a28209663b176cb7091775afbb94",
    "manifests": "92f64016ef43431ba329d75679b2860f14c74a3bcaa486fe93c789ce926a6244",
    "estimates": "de9f2a75f03723d9696187b696ad14a7b250b6a5c4072e9ef39cbba377e6612c",
    "upstream_parser": "e46d2e65ce0f49810d8dc0c72771ab93df984660ff3970a781ec9628e4f6e3cf",
    "model": "c4f43877e7379a11a503151a275a256f3dc1bb36c749b9f84cf695c5e9723237",
    "model_card": "8a1c47b8ff265ba3cda2082ae785264451164b01e2c54835f5957dd4a3a8e849"
  },
  "epistemic_limit": "Probabilidade histórica modelada; plataforma direta permanece não observada fora dos módulos especiais.",
  "claim_ceiling": "Estimativa model-based agregada de compatibilidade histórica com entrega por plataforma, calibrada em 2022T4/2024T3.",
  "created_at_utc": "2026-07-23T13:09:24.473280+00:00"
}
STATUS: CERTIFIED
MODELO: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/05_outputs/models/pnadc_historical_proxy/pnadc_historical_proxy_model_20260723T124000Z.joblib
PERÍODOS: ['2019q1', '2019q2', '2019q3', '2019q4', '2020q1', '2020q2', '2020q3', '2020q4', '2021q1', '2021q2', '2021q3', '2021q4', '2022q4', '2024q3']
REPORT: /content/drive/MyDrive/aCidadeAlgoritmica/SPINE-GPEv7/06_reports/pnadc_historical_proxy/pnadc_historical_proxy_report_20260723T124000Z.md

## 3. Inspeção das métricas temporais e estimativas

In [12]:
import pandas as pd

run_id = lock['run_id']
metrics_path = ROOT / f'05_outputs/tables/pnadc_historical_proxy/pnadc_proxy_temporal_metrics_{run_id}.csv'
rules_path = ROOT / f'05_outputs/tables/pnadc_historical_proxy/pnadc_proxy_rule_benchmark_{run_id}.csv'
estimates_path = Path(lock['estimates'])

metrics = pd.read_csv(metrics_path)
rules = pd.read_csv(rules_path)
estimates = pd.read_csv(estimates_path)

display(metrics)
display(rules)
display(estimates)

,model,train_year,test_year,n_test,n_positive,weighted_prevalence,roc_auc,average_precision,brier,null_brier,brier_skill,log_loss,ece_10
0,weighted_logit_occ_activity_position,2024,2022,178163,691,0.005208,0.980863,0.331738,0.003954,0.005181,0.236815,0.016074,5.287540e-04
1,weighted_logit_occ_activity_position,2022,2024,184157,778,0.005505,0.980062,0.374635,0.003986,0.005475,0.271932,0.016302,6.793733e-04
2,weighted_logit_occ_activity_position_calibrate...,0,0,362320,1469,0.005359,0.981253,0.349444,0.003916,0.005331,0.265323,0.015840,1.172943e-18
3,weighted_logit_extended_sensitivity,2024,2022,178163,691,0.005208,0.982918,0.372392,0.003912,0.005181,0.245040,0.015604,5.297994e-04
4,weighted_logit_extended_sensitivity,2022,2024,184157,778,0.005505,0.981921,0.389540,0.003968,0.005475,0.275281,0.015932,5.507342e-04
5,weighted_logit_extended_sensitivity_calibrated...,0,0,362320,1469,0.005359,0.982972,0.377126,0.003876,0.005331,0.272829,0.015465,2.150017e-18

,year,rule,n,n_positive,weighted_sensitivity,weighted_specificity,weighted_ppv,weighted_npv,weighted_accuracy
0,2022,occupation_compatible,178163,691,0.531010,0.938692,0.043379,0.997391,0.936568
1,2022,delivery_activity,178163,691,0.431591,0.997109,0.438705,0.997024,0.994164
2,2022,occupation_or_activity,178163,691,0.535719,0.938413,0.043557,0.997416,0.936316
3,2022,occupation_and_activity,178163,691,0.426882,0.997388,0.461083,0.997001,0.994416
4,2024,occupation_compatible,184157,778,0.561790,0.938108,0.047843,0.997421,0.936036
5,2024,delivery_activity,184157,778,0.459623,0.997019,0.460521,0.997009,0.994061
6,2024,occupation_or_activity,184157,778,0.563402,0.937908,0.047827,0.997430,0.935846
7,2024,occupation_and_activity,184157,778,0.458011,0.997219,0.476942,0.997000,0.994251

,period,estimand,total,total_se,share,share_se,n,n_eff,n_strata,n_psu
0,2019q1,model_expected_probability,3.162166e+05,7404.902800,0.003942,0.000091,201434,101639.770957,574,15060
1,2019q1,rule_occupation,4.769847e+06,66522.418921,0.059459,0.000775,201434,101639.770957,574,15060
2,2019q1,rule_activity,1.482716e+05,12933.224719,0.001848,0.000161,201434,101639.770957,574,15060
3,2019q1,rule_occ_or_activity,4.776935e+06,66597.844060,0.059547,0.000776,201434,101639.770957,574,15060
4,2019q1,rule_occ_and_activity,1.411835e+05,12593.250210,0.001760,0.000157,201434,101639.770957,574,15060
...,...,...,...,...,...,...,...,...,...,...
107,2024q3,rule_occ_or_activity,5.740229e+06,82087.275655,0.064852,0.000860,184157,95984.942282,573,15070
108,2024q3,rule_occ_and_activity,4.679431e+05,24295.117989,0.005287,0.000273,184157,95984.942282,573,15070
109,2024q3,model_class_threshold_0.25,3.933160e+05,22746.793421,0.004444,0.000256,184157,95984.942282,573,15070
110,2024q3,model_class_threshold_0.50,3.233188e+05,20759.682765,0.003653,0.000234,184157,95984.942282,573,15070
111,2024q3,model_class_threshold_0.75,0.000000e+00,0.000000,0.000000,0.000000,184157,95984.942282,573,15070

## 4. Expansão histórica opcional

Execute somente depois que o modo `auto` estiver certificado. O comando abaixo pode baixar e processar muitos arquivos grandes.

In [13]:
# Exemplo controlado: período pandêmico e pré-módulo direto.

expansion = subprocess.run(
     [
         sys.executable, str(SCRIPT),
         '--root', str(ROOT),
         '--mode', 'full',
         '--periods', '2019q1:2021q4',
         '--download-missing',
         '--chunk-rows', '50000',
         '--strict',
     ],
     check=False,
 )

## Regras de uso

- A soma ponderada das probabilidades é o estimando principal.
- A classe binária é somente análise de sensibilidade.
- A série histórica não preenche `SD14001`, `S140093` ou `platform_delivery_direct`.
- Comparações entre períodos são descritivas/model-based, não um desenho causal.